include:
  - board: nrfmicro/nrf52840/zmk
    shield: noirix44_left
    snippet: studio-rpc-usb-uart
    artifact-name: noirix44_left
  - board: nrfmicro/nrf52840/zmk
    shield: noirix44_right
    artifact-name: noirix44_right
  - board: nice_nano//zmk
    shield: monitor_adapter dongle_display
    artifact-name: noirix44_monitor_display
  - board: nrfmicro/nrf52840/zmk
    shield: settings_reset
    artifact-name: noirix44_settings_reset
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: noirix44_monitor_settings_reset
